# Usa una imagen base de OpenJDK
FROM openjdk:17-jdk-slim

# Copia el archivo JAR al contenedor
COPY target/quarkus-run.jar /app/quarkus-run.jar

# Define el directorio de trabajo
WORKDIR /app

# Expone el puerto que usará la aplicación
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["java", "-jar", "quarkus-run.jar"]