name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # o la rama que desees

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt-openj9'
          java-version: '17'

      - name: Print Java version
        run: java -version

      - name: Print Maven version
        run: mvn -v

      - name: Grant execute permission to mvnw
        run: chmod +x deploy-actions/mvnw
        
      - name: Build Quarkus project
        run: |
          cd deploy-actions
          ./mvnw package 

      - name: List target directory
        run: ls -la deploy-actions
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: List target directory
        run: ls -la
